# Generated by Django 3.0.8 on 2020-09-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='tagTimes',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
